<?php

namespace App\Services\Generator;

class MarkdownGenerator
{
    /**
     * Generate the markdown content for .llm.md.
     */
    public function generate(
        string $summary,
        string $techStack,
        string $directoryTree,
        array $entryPoints,
        string $features
    ): string {
        $output = "# Repository Overview\n\n";
        $output .= "> Auto-generated by Laravel Generator Command\n\n";

        $output .= "## Purpose\n\n";
        $output .= $summary."\n\n";

        $output .= "## Tech Stack\n\n";
        $output .= $techStack."\n\n";

        $output .= "## Directory Structure\n\n";
        $output .= "```\n";
        $output .= $directoryTree;
        $output .= "```\n\n";

        $output .= "## Key Entry Points\n\n";
        foreach ($entryPoints as $ep) {
            $output .= "- `$ep`\n";
        }
        $output .= "\n";

        $output .= "## Features (from tests)\n\n";
        $output .= $features."\n\n";

        return $output;
    }
}
